### PR TITLE
Update for Angular 4 and TypeScript 2.3

### PR DESCRIPTION
**Pull request by deepdivedylan**
Pubnub-Angular2 won't compile on TypeScript 2.3 without these modifications to the definition files. I made my best guess for `init` to return `any` since it's supposed to create a PubNub object. These are the errors I get below:

```node_modules/pubnub-angular2/lib/pubnub-angular2.d.ts(5,5): error TS7010: 'init', which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/pubnub-angular2/lib/wrapper.d.ts(5,5): error TS7010: 'init', which lacks return-type annotation, implicitly has an 'any' return type.```

### CODE REVIEW

**Comment by ManuelFernando** [comment]
Hi @deepdivedylan, thanks for your contribution I’ll check it as soon as I have a chance of what remain of this week.

**Comment by klaussilveira** [comment]
:+1:  for this.

**Comment by ManuelFernando** [comment]
Hi @deepdivedylan, Thanks for your contribution this change was done but not using this PR because this was done directly to master, this change will be available in the version 1.0.3
